# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "fddd9dc89a2aed1a91a8455b44b41c49"
name = "app-development"
application_url = "https://emerging-breath-transparent-read.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "algorithm-with-shop.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_customers,read_products,write_content,write_products,write_themes"

[auth]
redirect_urls = [
  "https://emerging-breath-transparent-read.trycloudflare.com/auth/callback",
  "https://emerging-breath-transparent-read.trycloudflare.com/auth/shopify/callback",
  "https://emerging-breath-transparent-read.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
