# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "695da14ec05f37f6cdd63a2b3c20b444"
name = "SEOfy - Complete SEO Expert"
application_url = "https://sponsored-handbook-mounts-impressive.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "algorithm-with-shop.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_customers,read_products,read_themes,write_content,write_products,write_themes"

[auth]
redirect_urls = [
  "https://sponsored-handbook-mounts-impressive.trycloudflare.com/auth/callback",
  "https://sponsored-handbook-mounts-impressive.trycloudflare.com/auth/shopify/callback",
  "https://sponsored-handbook-mounts-impressive.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
