# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4a8105f24e04b6b1e217541b65cb7b16"
name = "app-testing-bs23"
handle = "app-testing-bs23"
application_url = "https://spine-dust-semester-see.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "demo-store-kazi.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_themes,write_products,write_themes"

[auth]
redirect_urls = [
  "https://spine-dust-semester-see.trycloudflare.com/auth/callback",
  "https://spine-dust-semester-see.trycloudflare.com/auth/shopify/callback",
  "https://spine-dust-semester-see.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
